### ISSUE TITLE
Add license notice re: reproduced code

### ISSUE THREAD

**Issue by prestwich** [circlefin/evm-cctp-contracts#27]
This repo contains code derived from Nomad contracts without proper attribution and license information. As an author of the code involved, I'm happy that you found the work useful. Reuse of our code is praise

However, to use our work in compliance with the license, please add the appropriate MIT or Apache-2.0 license text (at your option) information to the files containing reproduced or derived code as well as a note in the README that some work is reproduced under the appropriate license

I have not done a full compliance audit of the code base, and do not have a full list of files in need of license notices. However, here is a simple example: 
- [This code region](https://github.com/circlefin/evm-cctp-contracts/blob/master/src/messages/Message.sol#L54-L65) is a slightly modified version of [this code region](https://github.com/nomad-xyz/monorepo/blob/main/packages/contracts-core/contracts/libs/Message.sol#L20-L30), but the file contains no indication that the work is used under either available FLOSS license. 

<img width="1771" alt="Screenshot 2023-10-01 at 17 09 48" src="https://github.com/circlefin/evm-cctp-contracts/assets/10149425/01e07811-fd3d-4cfe-9c78-1b1be78b47c9">

### TODOs

- [ ] Add license notice to files containing derivative or reproduced code
- [ ] Add note to README describing source and authorship of reproduced code
- [ ] Notify etherscan verification team of incomplete license information in hosted source files
- [ ] Optional: cite our work in public comms and/or documentation

**Comment by walkerq** [comment]
Hey @prestwich,

Thanks for raising this issue. We do import your library, [memview-sol](https://github.com/summa-tx/memview-sol) - we appreciate your work on that, and many other contributions to the space! Regarding other files in https://github.com/circlefin/evm-cctp-contracts, we have updated the license notice, and README, with attribution: https://github.com/circlefin/evm-cctp-contracts/pull/28.

We are also reaching out to Etherscan to hopefully get that license added.

**Comment by prestwich** [comment]
Thanks!
